# fly.toml app configuration file generated for macro-tracker-512 on 2023-10-31T00:56:52+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "macro-tracker-512"
primary_region = "syd"

[build]

[env]
  port = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
