name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  buildUI_deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd ./backend
      - run: npm run gh-actions:deploy:full
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}