name: Fly Deploy
on:
  push:
    branches:
      - gh_actions
jobs:
  buildUI_deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    CI: ""
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd ./frontend && npm install --silent
      - run: cd "./backend" && npm run build:ui
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}