name: Fly Deploy
on:
  push:
    branches:
      - gh_actions
jobs:
  buildUI_deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd ./backend
      - run: ls
      - run: cat package.json
      - run: npm run build:ui
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}